# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exportaconsulta.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 542)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_3.setStyleSheet("background-color: rgb(36, 190, 158);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lb_tit_principal = QtWidgets.QLabel(self.frame_3)
        self.lb_tit_principal.setGeometry(QtCore.QRect(240, 0, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lb_tit_principal.setFont(font)
        self.lb_tit_principal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_tit_principal.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.lb_tit_principal.setObjectName("lb_tit_principal")
        self.verticalLayout.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 210))
        self.frame.setStyleSheet("background-color: rgb(72, 160, 144);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lb_configs = QtWidgets.QLabel(self.frame)
        self.lb_configs.setGeometry(QtCore.QRect(0, 0, 71, 16))
        self.lb_configs.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.lb_configs.setWordWrap(False)
        self.lb_configs.setObjectName("lb_configs")
        self.lb_servidor = QtWidgets.QLabel(self.frame)
        self.lb_servidor.setGeometry(QtCore.QRect(10, 20, 55, 16))
        self.lb_servidor.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.lb_servidor.setObjectName("lb_servidor")
        self.lb_banco = QtWidgets.QLabel(self.frame)
        self.lb_banco.setGeometry(QtCore.QRect(10, 60, 55, 16))
        self.lb_banco.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.lb_banco.setObjectName("lb_banco")
        self.tx_servidor = QtWidgets.QLineEdit(self.frame)
        self.tx_servidor.setGeometry(QtCore.QRect(10, 40, 301, 22))
        self.tx_servidor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tx_servidor.setObjectName("tx_servidor")
        self.tx_banco = QtWidgets.QLineEdit(self.frame)
        self.tx_banco.setGeometry(QtCore.QRect(10, 80, 301, 22))
        self.tx_banco.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tx_banco.setObjectName("tx_banco")
        self.lb_user = QtWidgets.QLabel(self.frame)
        self.lb_user.setGeometry(QtCore.QRect(380, 30, 55, 16))
        self.lb_user.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.lb_user.setObjectName("lb_user")
        self.tx_user = QtWidgets.QLineEdit(self.frame)
        self.tx_user.setGeometry(QtCore.QRect(380, 50, 311, 22))
        self.tx_user.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tx_user.setObjectName("tx_user")
        self.tx_senha = QtWidgets.QLineEdit(self.frame)
        self.tx_senha.setGeometry(QtCore.QRect(380, 100, 311, 22))
        self.tx_senha.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tx_senha.setObjectName("tx_senha")
        self.lb_senha = QtWidgets.QLabel(self.frame)
        self.lb_senha.setGeometry(QtCore.QRect(380, 80, 41, 16))
        self.lb_senha.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.lb_senha.setObjectName("lb_senha")
        self.tx_nome_arquivo = QtWidgets.QLineEdit(self.frame)
        self.tx_nome_arquivo.setGeometry(QtCore.QRect(10, 130, 301, 22))
        self.tx_nome_arquivo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tx_nome_arquivo.setObjectName("tx_nome_arquivo")
        self.lb_nome_arquivo = QtWidgets.QLabel(self.frame)
        self.lb_nome_arquivo.setGeometry(QtCore.QRect(10, 110, 81, 16))
        self.lb_nome_arquivo.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.lb_nome_arquivo.setObjectName("lb_nome_arquivo")
        self.tx_local_salvar = QtWidgets.QLineEdit(self.frame)
        self.tx_local_salvar.setGeometry(QtCore.QRect(10, 180, 611, 22))
        self.tx_local_salvar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tx_local_salvar.setObjectName("tx_local_salvar")
        self.lb_local_salvar = QtWidgets.QLabel(self.frame)
        self.lb_local_salvar.setGeometry(QtCore.QRect(10, 160, 81, 16))
        self.lb_local_salvar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.lb_local_salvar.setObjectName("lb_local_salvar")
        self.btn_salva_conf = QtWidgets.QPushButton(self.frame)
        self.btn_salva_conf.setGeometry(QtCore.QRect(640, 180, 93, 21))
        self.btn_salva_conf.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.btn_salva_conf.setObjectName("btn_salva_conf")
        self.lb_formato = QtWidgets.QLabel(self.frame)
        self.lb_formato.setGeometry(QtCore.QRect(380, 130, 51, 16))
        self.lb_formato.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.lb_formato.setObjectName("lb_formato")
        self.btn_xlsx = QtWidgets.QRadioButton(self.frame)
        self.btn_xlsx.setGeometry(QtCore.QRect(380, 150, 95, 20))
        self.btn_xlsx.setObjectName("btn_xlsx")
        self.btn_csv = QtWidgets.QRadioButton(self.frame)
        self.btn_csv.setGeometry(QtCore.QRect(490, 150, 95, 20))
        self.btn_csv.setObjectName("btn_csv")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(72, 160, 144);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lb_consulta = QtWidgets.QLabel(self.frame_2)
        self.lb_consulta.setGeometry(QtCore.QRect(10, 0, 81, 16))
        self.lb_consulta.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.lb_consulta.setObjectName("lb_consulta")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 721, 231))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: italic 8pt \"Arial\";")
        self.textEdit.setObjectName("textEdit")
        self.btn_exportar = QtWidgets.QPushButton(self.frame_2)
        self.btn_exportar.setGeometry(QtCore.QRect(640, 260, 93, 21))
        self.btn_exportar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.btn_exportar.setObjectName("btn_exportar")
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_tit_principal.setText(_translate("MainWindow", "Exporta consultas"))
        self.lb_configs.setText(_translate("MainWindow", "Configurações"))
        self.lb_servidor.setText(_translate("MainWindow", "Servidor :"))
        self.lb_banco.setText(_translate("MainWindow", "Banco :"))
        self.lb_user.setText(_translate("MainWindow", "Usuario  :"))
        self.lb_senha.setText(_translate("MainWindow", "Senha :"))
        self.lb_nome_arquivo.setText(_translate("MainWindow", "Nome Arquivo:"))
        self.lb_local_salvar.setText(_translate("MainWindow", "Local Salvar :"))
        self.btn_salva_conf.setText(_translate("MainWindow", "Salvar"))
        self.lb_formato.setText(_translate("MainWindow", "Formato :"))
        self.btn_xlsx.setText(_translate("MainWindow", "xlsx"))
        self.btn_csv.setText(_translate("MainWindow", "csv"))
        self.lb_consulta.setText(_translate("MainWindow", "Consulta :"))
        self.btn_exportar.setText(_translate("MainWindow", "Exportar"))
